
package org.easyws.work.callee;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EasyServiceWork", targetNamespace = "http://callee.work.easyws.org/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface EasyServiceWork {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String receive(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
