
package org.easyws.work.callee;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;


import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EasyServiceWorkService", targetNamespace = "http://callee.work.easyws.org/", wsdlLocation = "http://localhost:9088/easyWS?wsdl")
public class EasyServiceWorkService
    extends Service
{

    private final static URL EASYSERVICEWORKSERVICE_WSDL_LOCATION;
    private final static WebServiceException EASYSERVICEWORKSERVICE_EXCEPTION;
    private final static QName EASYSERVICEWORKSERVICE_QNAME = new QName("http://callee.work.easyws.org/", "EasyServiceWorkService");
    
    //读取核心配置
    private static ApplicationContext ACT = new ClassPathXmlApplicationContext("easy.xml");
    
    //20秒连接超时
    private static int connectTimeout;
    //20秒响应超时
    private static int requestTimeout;

    

    
    static {
        URL url = null;
        WebServiceException e = null;
        
        EasyCallee callee = (EasyCallee) ACT.getBean("easyClient");
        
        try {
        	  url = new URL(callee.getAddress());
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EASYSERVICEWORKSERVICE_WSDL_LOCATION = url;
        EASYSERVICEWORKSERVICE_EXCEPTION = e;
        //初始化Client
        initClient(callee);
    }
    
    
    private static void initClient(EasyCallee callee){
    	connectTimeout = callee.getConnectTimeOut();
    	requestTimeout = callee.getReadTimeOut();
    }
    
    
    private static URL getWsdlLocation() {
        if (EASYSERVICEWORKSERVICE_EXCEPTION!= null) {
            throw EASYSERVICEWORKSERVICE_EXCEPTION;
        }
        return EASYSERVICEWORKSERVICE_WSDL_LOCATION;
    }

    
    /**
     * There is no Parameters, because Services is Interface and not Class
     * So there is no WebServiceFeature
     */
    
    public EasyServiceWorkService() {
        super(getWsdlLocation(), EASYSERVICEWORKSERVICE_QNAME);
    }
    

    public EasyServiceWorkService(URL wsdlLocation) {
        super(wsdlLocation, EASYSERVICEWORKSERVICE_QNAME);
    }



    public EasyServiceWorkService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }



    /**
     * 
     * @return
     *     returns EasyServiceWork
     */
    @WebEndpoint(name = "EasyServiceWorkPort")
    public EasyServiceWork getEasyServiceWorkPort() {
        return super.getPort(new QName("http://callee.work.easyws.org/", "EasyServiceWorkPort"), EasyServiceWork.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EasyServiceWork
     */
/*    @WebEndpoint(name = "EasyServiceWorkPort")
    public EasyServiceWork getEasyServiceWorkPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://callee.work.easyws.org/", "EasyServiceWorkPort"), EasyServiceWork.class, features);
    }*/

	
	public int getConnectTime(){
		return connectTimeout;
	}
	
	public int getRequestTime(){
		return requestTimeout;
	}
	


}
